version: "3"

services:
  ravendb:
    build: ravendb
    ports:
      - 8080:8080
      - 38888:38888
    networks:
      - backend
      - etl
      - frontend
    environment:
      - RAVEN_ARGS=--log-to-console
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=True
      - RAVEN_ServerUrl=http://0.0.0.0:8080
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_DataDir=RavenData
      - RAVEN_License_Path=/opt/settings/license.json
      - RAVEN_Features_Availability=Experimental
      - RAVEN_Indexing_MaxNumberOfConcurrentlyRunningIndexes=2
    volumes:
      - ./ravendb/settings:/opt/settings
      - ravendata:/opt/RavenDB/Server/RavenData
    restart:
      always

  init:
    build:
      context: ravendb
      target: resourcemodel
    networks:
      - backend
    depends_on:
      - ravendb
    entrypoint: ["dotnet", "Digitalisert.Dataplattform.ResourceModel.dll"]

  drupal:
    build: drupal
    ports:
      - 8181:80
    networks:
      - backend
      - frontend
    volumes:
      - ./drupal/config/sync:/opt/drupal/config/sync
      - ./drupal/sites/default/settings.local.php:/opt/drupal/web/sites/default/settings.local.php
      - drupalfiles:/opt/drupal/web/sites/default/files
    environment:
      - DRUPAL_DATABASE_NAME
      - DRUPAL_DATABASE_USERNAME
      - DRUPAL_DATABASE_PASSWORD
      - DRUPAL_DATABASE_HOST
      - DRUPAL_DATABASE_PORT
      - DRUPAL_HASH_SALT
    restart: always

  postgres:
    image: postgres:13.3
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    restart: always

networks:
  backend:
  etl:
  frontend:

volumes:
  ravendata:
  drupalfiles:
  pgdata:
