version: "3"

services:
  ravendb:
    build: ravendb
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_ARGS=--log-to-console
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=True
      - RAVEN_ServerUrl=http://0.0.0.0:8080
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_DataDir=RavenData
      - RAVEN_License_Path=/opt/settings/license.json
      - RAVEN_Features_Availability=Experimental
      - RAVEN_Indexing_MaxNumberOfConcurrentlyRunningIndexes=2
    volumes:
      - ./ravendb/settings:/opt/settings
      - ravendata:/opt/RavenDB/Server/RavenData
    restart:
      always

  drupal:
    build: drupal
    ports:
      - 8181:80
    volumes:
      - ./drupal/config/sync:/opt/drupal/config/sync
      - ./drupal/sites/default/settings.local.php:/opt/drupal/web/sites/default/settings.local.php
    environment:
      - DRUPAL_DATABASE_NAME
      - DRUPAL_DATABASE_USERNAME
      - DRUPAL_DATABASE_PASSWORD
      - DRUPAL_DATABASE_HOST
      - DRUPAL_DATABASE_PORT
      - DRUPAL_HASH_SALT

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD
    restart: always

volumes:
  ravendata: