FROM ravendb/ravendb:5.1.7-ubuntu.20.04-x64

COPY bin.tmp/net5.0/Geohash.dll /opt/RavenDB/Server/Geohash.dll
COPY bin.tmp/net5.0/MoreLinq.dll /opt/RavenDB/Server/MoreLinq.dll
COPY bin.tmp/net5.0/NetTopologySuite.dll /opt/RavenDB/Server/NetTopologySuite.dll
COPY bin.tmp/net5.0/ProjNET.dll /opt/RavenDB/Server/ProjNET.dll
COPY bin.tmp/net5.0/SmartFormat.dll /opt/RavenDB/Server/SmartFormat.dll

COPY bin.tmp/net5.0/ravendb.dll /opt/RavenDB/Server/ravendb.dll